name: cashsim

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["api", "--host", "0.0.0.0", "--port", "8000"]
    environment:

      CASHSIM_OTEL_ENABLED: "true"
      OTEL_SERVICE_NAME: "cashsim-api"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_EXPORTER_OTLP_INSECURE: "true"


      LOG_LEVEL: "INFO"
      LOG_FORMAT: "json"





    ports:
      - "8000:8000"
    depends_on:
      - otel-collector
    healthcheck:
      test:
        [
          "CMD",
          "bash",
          "-lc",
          'python -c "import urllib.request; urllib.request.urlopen(''http://localhost:8000/healthz'').read()"',
        ]
      interval: 10s
      timeout: 3s
      retries: 10

  ui:
    build:
      context: .
      dockerfile: Dockerfile

    command:
      ["ui", "--headless", "--server.address", "0.0.0.0", "--server.port", "8501"]
    environment:
      LOG_LEVEL: "INFO"
      LOG_FORMAT: "json"

      CASHSIM_API_BASE_URL: "http://api:8000"
    ports:
      - "8501:8501"

  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.141.0
    command: ["--config=/etc/otelcol/config.yaml"]
    volumes:
      - ./ops/otel/otelcol-config.yaml:/etc/otelcol/config.yaml:ro
    ports:
      - "4317:4317"
      - "4318:4318"
      - "8889:8889"

  jaeger:
    image: jaegertracing/all-in-one:1.55
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
      METRICS_STORAGE_TYPE: "prometheus"
      PROMETHEUS_SERVER_URL: "http://prometheus:9090"
    command:
      - "--prometheus.query.support-spanmetrics-connector=true"
    ports:
      - "16686:16686"
      - "14268:14268"
      - "4319:4317"

  prometheus:
    image: prom/prometheus:latest
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
    volumes:
      - ./ops/otel/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./ops/grafana/provisioning:/etc/grafana/provisioning:ro
    ports:
      - "3000:3000"
    depends_on:
      - prometheus

networks:
  default:
    name: cashsim
