[mypy]
python_version = 3.12
warn_unused_ignores = True

[mypy-streamlit.*]
ignore_missing_imports = True

[mypy-gspread.*]
ignore_missing_imports = True

[mypy-google.*]
ignore_missing_imports = True

[mypy-gspread_dataframe.*]
ignore_missing_imports = True

[mypy-pydantic.*]
ignore_missing_imports = True

[mypy-typing_extensions.*]
ignore_missing_imports = True

[mypy-hypothesis.*]
ignore_missing_imports = True

[mypy-great_expectations.*]
ignore_missing_imports = True

[mypy-great_expectations]
ignore_missing_imports = True
