[gcp_service_account]
type = "service_account"
project_id = "YOUR-PROJECT-ID"
private_key_id = "REDACTED"
private_key = "-----BEGIN PRIVATE KEY-----\n...paste with literal \\n line breaks...\n-----END PRIVATE KEY-----\n"
client_email = "svc-account@YOUR-PROJECT-ID.iam.gserviceaccount.com"
client_id = "12345678901234567890"
token_uri = "https://oauth2.googleapis.com/token"
